### 회원가입
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "동그라미2",
  "role": "USER"
}


### 조회
GET localhost:8080/api/users


### 로그인 USER
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "user",
  "password": "1111"
}


### 로그인 MANAGER
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "manager",
  "password": "1111"
}


### 메세지
GET http://localhost:8080/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest